// Pictures parents can pick for a chore, grouped for browsing, with search words for each.
// Emoji only go up to Unicode 13 so they render on older Android phones. There is no emoji
// for some chores (dishwasher, vacuum, lawn mower), so the closest ones carry those words.

export interface ChoreIcon {
  emoji: string;
  /** Lowercase search words. */
  words: string;
}

export interface ChoreIconGroup {
  title: string;
  icons: ChoreIcon[];
}

const g = (title: string, list: [string, string][]): ChoreIconGroup => ({
  title,
  icons: list.map(([emoji, words]) => ({ emoji, words })),
});

export const CHORE_ICON_GROUPS: ChoreIconGroup[] = [
  g('Kitchen', [
    ['🍽️', 'dishes plates dishwasher set table clear table dinner'],
    ['🍴', 'cutlery silverware fork knife set table dishwasher'],
    ['🥄', 'spoon cutlery silverware dishwasher'],
    ['🧽', 'sponge wash dishes scrub wipe counters dishwasher clean'],
    ['🥣', 'bowl cereal breakfast dishes'],
    ['🍳', 'cook breakfast eggs pan stove'],
    ['🥘', 'cook dinner pan pot stove'],
    ['🍲', 'soup dinner cook pot'],
    ['🍝', 'pasta spaghetti dinner cook'],
    ['🍕', 'pizza dinner'],
    ['🥪', 'sandwich lunch pack lunch'],
    ['🍱', 'lunchbox pack lunch'],
    ['🥗', 'salad dinner vegetables'],
    ['🥕', 'vegetables carrot peel chop'],
    ['🍎', 'fruit snack apple'],
    ['🍞', 'bread toast breakfast'],
    ['🧁', 'bake baking cupcake'],
    ['🍪', 'cookies bake baking'],
    ['🥛', 'milk drink'],
    ['☕', 'coffee tea drink'],
    ['🫖', 'teapot tea kettle'],
    ['🥤', 'cup drink'],
    ['🧃', 'juice box drink lunch'],
    ['🧊', 'ice freezer fridge'],
    ['🧂', 'salt spices pantry'],
  ]),
  g('Cleaning', [
    ['🧹', 'sweep broom floor vacuum clean'],
    ['🪣', 'bucket mop floor clean'],
    ['💨', 'vacuum dust air'],
    ['✨', 'clean shine dust polish tidy sparkle'],
    ['🧼', 'soap wash hands scrub clean dishwasher'],
    ['🧴', 'spray bottle cleaner lotion'],
    ['🗑️', 'trash garbage bin take out'],
    ['♻️', 'recycling recycle bins'],
    ['🚽', 'toilet bathroom clean scrub'],
    ['🧻', 'toilet paper bathroom restock'],
    ['🪠', 'plunger toilet bathroom'],
    ['🛁', 'bathtub tub bathroom scrub'],
    ['🚿', 'shower bathroom clean'],
    ['🪞', 'mirror bathroom wipe'],
    ['🪟', 'window wash windows'],
    ['🚰', 'sink tap water'],
    ['🧤', 'gloves clean'],
    ['🧯', 'fire extinguisher smoke alarm check safety'],
  ]),
  g('Laundry & bedroom', [
    ['🧺', 'laundry basket clothes put away'],
    ['👕', 'shirt clothes fold laundry'],
    ['👖', 'jeans pants clothes fold'],
    ['🩳', 'shorts clothes fold'],
    ['🧦', 'socks match laundry'],
    ['👗', 'dress clothes hang'],
    ['🧥', 'coat jacket hang up'],
    ['👟', 'shoes put away'],
    ['🛏️', 'bed make bed bedroom sheets'],
    ['🛌', 'bedtime sleep bed'],
    ['🧸', 'toys teddy tidy room pick up'],
    ['🪀', 'toys yo-yo tidy'],
    ['🧩', 'puzzle toys games tidy'],
    ['🎒', 'backpack school bag pack'],
    ['🧵', 'sewing thread mend'],
    ['🧷', 'pin mend clothes'],
  ]),
  g('Yard & outdoors', [
    ['🌱', 'lawn grass mow lawn mower seedling garden'],
    ['🚜', 'tractor mow lawn mower yard'],
    ['🌿', 'weeds weeding garden trim hedge lawn'],
    ['🍂', 'leaves rake fall autumn yard'],
    ['🍁', 'leaves rake fall maple'],
    ['🌳', 'tree yard trim'],
    ['🌷', 'flowers garden plant'],
    ['🌻', 'garden sunflower flowers'],
    ['🪴', 'plant water plants houseplant'],
    ['💧', 'water plants garden hose'],
    ['❄️', 'snow shovel winter driveway'],
    ['⛄', 'snow shovel winter'],
    ['🪓', 'axe chop wood firewood'],
    ['🪵', 'wood logs firewood'],
    ['🔥', 'fire grill bbq fireplace'],
    ['🏡', 'house yard outside'],
    ['🚗', 'car wash car vacuum car'],
    ['🚲', 'bike bicycle'],
    ['🏊', 'pool swim clean pool'],
    ['📬', 'mail mailbox get mail'],
    ['📦', 'package boxes recycling'],
    ['⛏️', 'dig garden'],
    ['🪨', 'rocks stones yard'],
  ]),
  g('Pets', [
    ['🐕', 'dog walk dog pet'],
    ['🐶', 'dog puppy feed dog pet'],
    ['🦴', 'bone dog food treat'],
    ['🐾', 'paws pet litter box poop scoop'],
    ['🐈', 'cat litter box pet'],
    ['🐱', 'cat feed cat pet'],
    ['🐟', 'fish feed fish tank'],
    ['🐠', 'fish aquarium tank'],
    ['🐹', 'hamster cage pet'],
    ['🐰', 'rabbit bunny cage pet'],
    ['🐦', 'bird cage pet'],
    ['🐢', 'turtle tank pet'],
    ['🦎', 'lizard reptile tank pet'],
    ['🐴', 'horse barn'],
    ['🐔', 'chickens eggs coop'],
  ]),
  g('Errands & house', [
    ['🛒', 'groceries grocery shopping cart store'],
    ['🛍️', 'shopping bags errands'],
    ['🧾', 'bills receipt pay'],
    ['💳', 'pay bills card'],
    ['💰', 'money budget allowance'],
    ['🏦', 'bank'],
    ['⛽', 'gas fuel car'],
    ['💊', 'medicine pills vitamins'],
    ['🏥', 'doctor appointment'],
    ['📮', 'post office mail letters'],
    ['🔧', 'fix repair wrench'],
    ['🔨', 'hammer fix build'],
    ['🪛', 'screwdriver fix repair'],
    ['🧰', 'toolbox tools fix'],
    ['🪜', 'ladder gutters'],
    ['💡', 'light bulb lights'],
    ['🔋', 'battery charge devices'],
    ['🔑', 'keys lock up'],
    ['🚪', 'door lock'],
    ['🛋️', 'couch sofa living room tidy'],
    ['🪑', 'chair furniture'],
    ['🗓️', 'calendar plan schedule'],
    ['📞', 'phone call'],
    ['👶', 'baby babysit watch sibling'],
    ['🍼', 'bottle baby feed'],
  ]),
  g('School & self-care', [
    ['📚', 'homework books study school'],
    ['✏️', 'homework pencil write'],
    ['📝', 'notes write homework'],
    ['📖', 'read reading book'],
    ['🧮', 'math homework'],
    ['💻', 'computer homework'],
    ['🎹', 'piano practice music'],
    ['🎸', 'guitar practice music'],
    ['🎻', 'violin practice music'],
    ['🥁', 'drums practice music'],
    ['🎨', 'art draw paint'],
    ['⚽', 'soccer sports practice'],
    ['🏀', 'basketball sports practice'],
    ['🏃', 'run exercise'],
    ['💪', 'exercise workout'],
    ['🧘', 'yoga stretch calm'],
    ['🦷', 'teeth brush teeth'],
    ['🪥', 'toothbrush brush teeth'],
    ['🛀', 'bath bathtime'],
    ['💇', 'hair brush hair'],
    ['⏰', 'alarm wake up morning'],
    ['💤', 'sleep bedtime nap'],
  ]),
  g('Other', [
    ['⭐', 'star special'],
    ['✅', 'check done'],
    ['❤️', 'heart kindness'],
    ['🤝', 'help helping'],
    ['🎁', 'gift present wrap'],
    ['🎉', 'party celebrate'],
    ['🏠', 'home house'],
    ['📌', 'pin reminder'],
    ['🔔', 'bell reminder'],
  ]),
];

export const DEFAULT_CHORE_ICON = '🛏️';

/** Groups narrowed to icons whose words contain every word typed. */
export function searchChoreIcons(query: string): ChoreIconGroup[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return CHORE_ICON_GROUPS;
  return CHORE_ICON_GROUPS.map((group) => ({
    ...group,
    icons: group.icons.filter((i) => terms.every((t) => i.words.includes(t))),
  })).filter((group) => group.icons.length > 0);
}
